# Generated by Django 5.2.5 on 2026-03-13 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0002_physician_type_locum_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physician',
            options={'ordering': ['physician_type', 'last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='physician',
            name='specialty',
        ),
        migrations.AlterField(
            model_name='coverageassignment',
            name='covered_physician',
            field=models.ForeignKey(blank=True, help_text='Regular physician being covered (optional)', limit_choices_to={'physician_type': 'regular'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covered_assignments', to='coverage_tracker.physician'),
        ),
        migrations.AlterField(
            model_name='coverageassignment',
            name='covering_physician',
            field=models.ForeignKey(help_text='Locum physician providing coverage', limit_choices_to={'physician_type': 'locum'}, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_assignments', to='coverage_tracker.physician'),
        ),
        migrations.AlterField(
            model_name='coverageassignment',
            name='daily_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Override the locum's standard daily rate for this specific assignment", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='physician',
            name='total_vacation_days',
            field=models.PositiveIntegerField(default=20, help_text='Annual vacation day allocation (for regular physicians)'),
        ),
        migrations.AlterField(
            model_name='physicianavailability',
            name='physician',
            field=models.ForeignKey(limit_choices_to={'physician_type': 'locum'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='coverage_tracker.physician'),
        ),
    ]
