# Generated by Django 5.2.5 on 2026-03-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0003_alter_physician_options_remove_clinic_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
