# Generated by Django 5.2.5 on 2026-03-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0004_alter_timeoffrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
