# Generated by Django 5.2.5 on 2026-03-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0005_alter_timeoffrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
