# Generated by Django 5.2.5 on 2026-04-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
