# Generated by Django 5.2.5 on 2026-04-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0009_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='regular_physicians',
            field=models.ManyToManyField(blank=True, help_text='Regular and PSA physicians permanently assigned to this clinic', limit_choices_to={'physician_type__in': ['regular', 'psa']}, related_name='assigned_clinics', to='coverage_tracker.physician'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('physician_admin', 'Physician Administrator'), ('physician', 'Physician')], default='physician', max_length=20),
        ),
    ]
