# Generated by Django 5.2.5 on 2026-04-22 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0010_alter_clinic_regular_physicians_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverageassignment',
            name='covered_physician',
            field=models.ForeignKey(blank=True, help_text='NROC physician being covered (optional)', limit_choices_to={'physician_type': 'regular'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covered_assignments', to='coverage_tracker.physician'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='physician_type',
            field=models.CharField(choices=[('regular', 'NROC Physician'), ('locum', 'Locum / Covering Physician'), ('psa', 'PSA Physician')], default='regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='physician',
            name='total_vacation_days',
            field=models.PositiveIntegerField(default=20, help_text='Annual vacation day allocation (for NROC physicians)'),
        ),
    ]
