# Generated by Django 5.2.5 on 2026-04-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0011_alter_coverageassignment_covered_physician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for locum physicians. Daily pay = hourly rate × hours worked.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='regular_physicians',
            field=models.ManyToManyField(blank=True, help_text='NROC and PSA physicians permanently assigned to this clinic', limit_choices_to={'physician_type__in': ['regualr', 'psa']}, related_name='assigned_clinics', to='coverage_tracker.physician'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy / standard daily rate (kept for reference — hourly rate is used for pay)', max_digits=10, null=True),
        ),
    ]
