# Generated by Django 5.2.5 on 2026-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0012_physician_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageassignment',
            name='hourly_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Override the locum's standard hourly rate for this specific assignment", max_digits=10, null=True),
        ),
    ]
