# Generated by Django 5.2.5 on 2026-04-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0013_coverageassignment_hourly_rate_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageassignment',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
