# Generated by Django 5.2.5 on 2026-04-24 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0014_coverageassignment_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scope',
            field=models.CharField(choices=[('nroc', 'NROC Physicians'), ('psa', 'PSA Physicians'), ('all', 'Both NROC and PSA')], default='nroc', help_text='Which physician group this login represents.', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='physician',
            field=models.OneToOneField(blank=True, help_text='Optional: link to a specific physician record (not required for shared logins).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coverage_tracker.physician'),
        ),
    ]
