# Generated by Django 5.2.5 on 2026-05-01 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0015_userprofile_scope_alter_userprofile_physician'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coverageassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coverageassignment',
            name='no_coverage_needed',
            field=models.BooleanField(default=False, help_text='Mark this day as resolved without assigning a locum (e.g., half day, shift swapped).'),
        ),
        migrations.AddField(
            model_name='coverageassignment',
            name='no_coverage_reason',
            field=models.CharField(blank=True, help_text="Required reason when 'no coverage needed' is set (e.g., 'half day', 'physician swapped shift').", max_length=255),
        ),
        migrations.AlterField(
            model_name='coverageassignment',
            name='covering_physician',
            field=models.ForeignKey(blank=True, help_text='Locum physician providing coverage', limit_choices_to={'physician_type': 'locum'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_assignments', to='coverage_tracker.physician'),
        ),
        migrations.AddConstraint(
            model_name='coverageassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('covering_physician__isnull', False)), fields=('clinic', 'covering_physician', 'date'), name='unique_clinic_locum_date_when_assigned'),
        ),
        migrations.AddConstraint(
            model_name='coverageassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('no_coverage_needed', True)), fields=('covered_physician', 'date'), name='unique_no_coverage_per_covered_physician_per_day'),
        ),
    ]
