# Generated by Django 5.2.5 on 2026-05-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0016_alter_coverageassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='regular_physicians',
            field=models.ManyToManyField(blank=True, help_text='NROC and PSA physicians permanently assigned to this clinic', limit_choices_to={'physician_type__in': ['regular', 'psa']}, related_name='assigned_clinics', to='coverage_tracker.physician'),
        ),
    ]
