# Generated by Django 5.2.5 on 2026-05-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0017_alter_clinic_regular_physicians'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('nroc', 'NROC'), ('psa', 'PSA')], help_text='Which physician group this on-call entry belongs to.', max_length=10)),
                ('date', models.DateField(help_text='Date of on-call coverage.')),
                ('shift', models.CharField(choices=[('weekend', 'Weekend'), ('holiday', 'Holiday')], default='full', help_text='Type of on-call shift.', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('physician', models.ForeignKey(help_text='Physician scheduled to be on call.', limit_choices_to={'physician_type__in': ['regular', 'psa']}, on_delete=django.db.models.deletion.CASCADE, related_name='on_call_entries', to='coverage_tracker.physician')),
            ],
            options={
                'ordering': ['date', 'group', 'shift'],
                'constraints': [models.UniqueConstraint(fields=('group', 'date', 'physician', 'shift'), name='unique_oncall_per_group_date_physician_shift')],
            },
        ),
    ]
