# Generated by Django 5.2.5 on 2026-05-22 21:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0018_oncallschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncallschedule',
            options={'ordering': ['weekend_start_date', 'group']},
        ),
        migrations.RemoveConstraint(
            model_name='oncallschedule',
            name='unique_oncall_per_group_date_physician_shift',
        ),
        migrations.RemoveField(
            model_name='oncallschedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='oncallschedule',
            name='shift',
        ),
        migrations.AddField(
            model_name='oncallschedule',
            name='weekend_start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Saturday that starts the weekend (Sunday is implied).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oncallschedule',
            name='physician',
            field=models.ForeignKey(help_text='Physician scheduled to be on call this weekend.', limit_choices_to={'physician_type__in': ['regular', 'psa']}, on_delete=django.db.models.deletion.CASCADE, related_name='on_call_entries', to='coverage_tracker.physician'),
        ),
        migrations.AddConstraint(
            model_name='oncallschedule',
            constraint=models.UniqueConstraint(fields=('group', 'weekend_start_date', 'physician'), name='unique_oncall_per_group_weekend_physician'),
        ),
    ]
