# Generated by Django 5.2.5 on 2026-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0019_alter_oncallschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('physician_admin', 'Physician Administrator'), ('physician', 'Physician'), ('nursing', 'Nursing')], default='physician', max_length=20),
        ),
    ]
