# Generated by Django 5.1.15 on 2026-07-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0020_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncallschedule',
            name='weekend_start_date',
            field=models.DateField(help_text='Monday that starts the on-call week (runs through Sunday).'),
        ),
    ]
