# Generated by Django 5.1.15 on 2026-07-09 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0021_alter_oncallschedule_weekend_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='total_cme_days',
            field=models.PositiveIntegerField(default=5, help_text='Annual CME / education day allocation'),
        ),
        migrations.AlterField(
            model_name='oncallschedule',
            name='physician',
            field=models.ForeignKey(help_text='Physician scheduled to be on call this week.', limit_choices_to={'physician_type__in': ['regular', 'psa']}, on_delete=django.db.models.deletion.CASCADE, related_name='on_call_entries', to='coverage_tracker.physician'),
        ),
    ]
