# Generated by Django 6.0.7 on 2026-07-16 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0022_physician_total_cme_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], help_text='Weekday (matches Python date.weekday(): Monday=0)')),
                ('session', models.CharField(choices=[('am', 'Morning'), ('pm', 'Afternoon')], max_length=2)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule', to='coverage_tracker.clinic')),
                ('physician', models.ForeignKey(limit_choices_to={'physician_type__in': ['regular', 'psa']}, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_schedule', to='coverage_tracker.physician')),
            ],
            options={
                'ordering': ['physician', 'day_of_week', 'session'],
                'constraints': [models.UniqueConstraint(fields=('physician', 'day_of_week', 'session'), name='one_clinic_per_physician_half_day')],
            },
        ),
    ]
