# Generated by Django 5.1.15 on 2026-07-23 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0023_clinicschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('full', 'Full day'), ('am', 'Morning'), ('pm', 'Afternoon')], default='full', max_length=4)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(help_text='Where the physician will work on this date', on_delete=django.db.models.deletion.CASCADE, related_name='day_reassignments', to='coverage_tracker.clinic')),
                ('physician', models.ForeignKey(limit_choices_to={'physician_type__in': ['regular', 'psa']}, on_delete=django.db.models.deletion.CASCADE, related_name='day_reassignments', to='coverage_tracker.physician')),
            ],
            options={
                'ordering': ['date', 'physician'],
                'constraints': [models.UniqueConstraint(fields=('physician', 'date', 'session'), name='one_reassignment_per_physician_date_session')],
            },
        ),
    ]
