# Generated by Django 5.1.7 on 2026-08-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0024_dayreassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('physician_admin', 'Physician Administrator'), ('physician', 'Physician'), ('nursing', 'Clinical')], default='physician', max_length=20),
        ),
    ]
