# Generated by Django 5.1.15 on 2026-08-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverage_tracker', '0025_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='availability_notes',
            field=models.TextField(blank=True, help_text="Free-text availability note shown on the availability page (e.g. 'Out until October — maternity leave')."),
        ),
    ]
