# Generated by Django 5.1.15 on 2026-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coverage_tracker", "0028_physician_phone_contact_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="regular_physicians",
            field=models.ManyToManyField(
                blank=True,
                help_text="NROC, PSA and locum physicians permanently assigned to this clinic. Locums assigned here are simply scheduled staff — they never request or need time off.",
                limit_choices_to={"physician_type__in": ["regular", "psa", "locum"]},
                related_name="assigned_clinics",
                to="coverage_tracker.physician",
            ),
        ),
    ]
