# Generated by Django 5.1.15 on 2026-09-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coverage_tracker", "0029_clinic_regular_physicians_allow_locums"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="regular_physicians",
            field=models.ManyToManyField(
                blank=True,
                help_text="NROC and PSA physicians permanently assigned to this clinic",
                limit_choices_to={"physician_type__in": ["regular", "psa"]},
                related_name="assigned_clinics",
                to="coverage_tracker.physician",
            ),
        ),
    ]
